name: 🐛 Bug Report
description: Report a bug or issue with Self-Streme
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us fix it.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Execute command '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Self-Streme Version
      description: What version are you running?
      options:
        - 2.0 (latest)
        - 1.x (older)
        - main branch (git)
        - Unknown
    validations:
      required: true

  - type: input
    id: nodejs
    attributes:
      label: Node.js Version
      description: Output of `node --version`
      placeholder: v18.0.0
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      options:
        - Linux
        - macOS
        - Windows
        - Docker
        - Other
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant parts of your .env file (DO NOT include API keys!)
      placeholder: |
        ENABLE_INSTANT_STREAMING=true
        ENABLE_PARALLEL_RACE=true
        # etc
      render: shell

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant log output (set LOG_LEVEL=debug for more details)
      placeholder: Paste your logs here
      render: shell

  - type: dropdown
    id: premium
    attributes:
      label: Using Premium Service?
      description: Are you using a premium debrid service?
      options:
        - No (free sources only)
        - Yes (Real-Debrid)
        - Yes (AllDebrid)
        - Yes (Premiumize)
        - Yes (Google Drive)

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      description: Please confirm you have done the following
      options:
        - label: I have searched for existing issues
          required: true
        - label: I am using the latest version
          required: false
        - label: I have enabled debug logging (LOG_LEVEL=debug)
          required: false
        - label: I have removed all API keys from logs/config
          required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, etc.)
      placeholder: Any additional information that might help
